version: "3.9"
services:
  server:
    image: springboot/parking-control
    build:
      context: .
    ports:
    - "8001:8080"
  database:
    image: postgres:alpine
    restart: always
    env_file: .env
    ports:
      - "5001:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local